# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  # Make sure the work directory is clean
  before_all do |lane, options|
    ensure_git_branch(branch: "master")
    ensure_git_status_clean
  end

  desc "Deploy a new version to Google Play"
  lane :deploy do |options|
    gradle(task: 'clean')
    gradle(task: 'assemble', flavor: 'prod', build_type: 'release')
    upload_to_play_store(
      track: 'internal', 
      skip_upload_metadata: !options[:metadata],
      skip_upload_images: !options[:images],
      skip_upload_screenshots: !options[:images],
      apk: 'app/build/outputs/apk/prod/release/app-prod-release.apk'
    )
    create_version_tag(env: 'play')
    bump_version_code
    push_changes
  end

  desc "Bump the major version of the application"
  lane :bump_major do
    major, minor, patch = read_version_name()
    write_version_name(major + 1, 0, 0)
    create_version_commit
  end

  desc "Bump the minor version of the application"
  lane :bump_minor do
    major, minor, patch = read_version_name()
    write_version_name(major, minor + 1, 0)
    create_version_commit
  end

  desc "Bump the patch version of the application"
  lane :bump_patch do
    major, minor, patch = read_version_name()
    write_version_name(major, minor, patch + 1)
    create_version_commit
  end

  private_lane :bump_version_code do
    version_code = read_version_code() + 1
    write_version_code(version_code)
    git_commit(path: 'version.properties', message: "Bump versionCode to #{version_code}")
  end

  private_lane :create_version_commit do
    current_version = read_version_name().join('.')
    git_commit(path: 'version.properties', message: "Bump version to #{current_version}")
  end

  private_lane :create_version_tag do |options|
    tag_name = options[:env] + '/' + read_version_name().join('.')
    add_git_tag(tag: tag_name)
    push_git_tags(tag: tag_name)
  end

  private_lane :push_changes do |options|
    push_to_git_remote(tags: false)
  end

end

$version_file = '../version.properties'

def read_version_name()
  content = File.read($version_file)
  major = /major=(\d+)/.match(content).captures[0].to_i
  minor = /minor=(\d+)/.match(content).captures[0].to_i
  patch = /patch=(\d+)/.match(content).captures[0].to_i
  return major, minor, patch
end

def write_version_name(major, minor, patch)
  lines = IO.readlines($version_file).map do |line|
    if line.start_with?('major=')
      "major=#{major}"
    elsif line.start_with?('minor=')
      "minor=#{minor}"
    elsif line.start_with?('patch=')
      "patch=#{patch}"
    else
      line
    end
  end
  File.open($version_file, 'w') do |file|
    file.puts lines
  end
end

def read_version_code()
  content = File.read($version_file)
  version_code = /code=(\d+)/.match(content).captures[0].to_i
  return version_code
end

def write_version_code(code)
  lines = IO.readlines($version_file).map do |line|
    if line.start_with?('code=')
      "code=#{code}"
    else
      line
    end
  end
  File.open($version_file, 'w') do |file|
    file.puts lines
  end
end
